/*!
* Plugin: jQuery AJAX-ZOOM, batch.js
* Copyright: Copyright (c) 2010-2018 Vadim Jacobi
* License Agreement: http://www.ajax-zoom.com/index.php?cid=download
* Extension Version: 2.3
* Extension Date: 2018-08-30
* URL: http://www.ajax-zoom.com
* Documentation: http://www.ajax-zoom.com/index.php?cid=docs
*/


(function(a){a.zoomBatch.shortMsg=function(b){a(".btn").blur();var c=a('<div class="batchShortMsg"><div class="alert alert-success">'+b+"</div></div>").bind("click",function(){c.fadeOut(100,function(){c.remove()})});c.prependTo("body");setTimeout(function(){c.length&&c.fadeOut(100,function(){c.remove()})},1500)};a.zoomBatch.isRunningMsg=function(b){a.zoomBatch.shortMsg(b||"Batch is running, please wait.")};a.zoomBatch.selectAllCheckbox=function(b){b=a("#"+b+" input[type=checkbox]");a.zoomBatch.checkBoxToggle(b)};
a.zoomBatch.selectAllCheckboxFolders=function(b){b=a("#"+b+" .leftFrameFolder input[type=checkbox]");a.zoomBatch.checkBoxToggle(b)};a.zoomBatch.selectAllCheckboxImages=function(b){b=a("#"+b+" .leftFrameTable input[type=checkbox]");a.zoomBatch.checkBoxToggle(b)};a.zoomBatch.checkBoxToggle=function(b){var c=!1,d=!1;b.each(function(){a(this).is(":checked")?c=!0:d=!0;if(c&&d)return!1});c&&d||d?b.attr({checked:!0}):c&&!d&&b.attr({checked:!1})};a.zoomBatch.deselectAllCheckbox=function(b){a("#"+b+" input[type=checkbox]").attr({checked:!1})};
a.zoomBatch.toggleCheckBox=function(b){b=a("#"+b);b.is(":checked")?b.attr({checked:!1}):b.attr({checked:!0})};a.zoomBatch.smartSelect=function(b){a.zoomBatch.deselectAllCheckbox("passFiles");var c=0,d=0;a("#leftFrameTable tbody tr").each(function(){var b=a(this).html();d++;0<b.indexOf(a.zoomBatch.batch.iconNames.Error)&&(b=a(this).attr("id").split("d").join(""),a("#f"+b).attr({checked:!0}),c++)});return b?!0:0==c&&0!=d?(alert("Everything has been done already!"),!1):0==d?(alert("No images in this folder or selection!"),
!1):!0};a.zoomBatch.reload=function(){a.zoomBatch.changeDir(a.zoomBatch.currentDir||"HOME")};a.zoomBatch.getSettingsInfo=function(){a.ajax({url:a.zoomBatch.batch.selfFile+"?getSettingsInfo=1",timeout:36E4,cache:!1,success:function(b){a("#infoSettings").empty().append(b);a("#getSettingsInfoBtn").blur()}})};a.zoomBatch.bc=function(b){var c=a("#bci");c.empty();if("HOME"!=b){b=b.split("_");var d=[],e="";a.each(b,function(a,b){e=e?e+("_"+b):"1";d.push(e)});a.each(d,function(b,e){var f=a("<a />");"1"==
e?f.html('<i class="fa fa-home" aria-hidden="true"></i> HOME').attr("href","javascript: void(0)").bind("click",function(){a.zoomBatch.changeDir("HOME")}):f.html(a.zoomBatch.dirTreeArray[e].DIR_NAME).attr("href","javascript: void(0)").bind("click",function(){a.zoomBatch.changeDir(e)});b+1!=d.length?(c.append(f),c.append(' <i class="fa fa-arrow-right" aria-hidden="true"></i> ')):a("<a />").attr("href","javascript: void(0)").html(f.html()).bind("click",a.zoomBatch.reload).appendTo(c)})}else a("<span />").html('<i class="fa fa-home" aria-hidden="true"></i> HOME').appendTo(c)};
a.zoomBatch.submitNewExampleValue=function(){var b=a("#batchSettingExample").find("input.form-control").val();b&&a.ajax({url:a.zoomBatch.batch.selfFile+"?changeExampleValue="+b,timeout:36E4,cache:!1,success:function(b){a("#batchSettingExample").find("input.form-control").val(b);a("#batchViewPlayerExampleValue").html(b);a.zoomBatch.batch.exampleValue=b;a.zoomBatch.reload();a.zoomBatch.shortMsg("Setting has been submitted.")}})};a.zoomBatch.submitStartPicBatch=function(b){b=b||a("#batchSettingStartPic").find("input.form-control").val();
0!==b.indexOf("/")?alert("Path must start with /"):b?(a.zoomBatch.changeStartPicBatch(b),a.zoomBatch.shortMsg("Setting has been submitted")):alert("Please enter a value")};a.zoomBatch.changeStartPicBatch=function(b,c){a.zoomBatch.dirLoaderStart();a.ajax({url:a.zoomBatch.batch.selfFile+"?changeStartPicBatch="+b,timeout:36E4,cache:!1,success:function(c){a("#batchSettingStartPic").find("input.form-control").val(b);a.zoomBatch.reloadDirTree()}})};a.zoomBatch.reloadDirTree=function(b){a.zoomBatch.dirLoaderStart();
a.zoomBatch.dirLoaderOverlayStart();a.ajax({url:a.zoomBatch.batch.selfFile+"?reloadDirTree=1",timeout:36E4,cache:!1,dataType:"script",success:function(c){a.zoomBatch.changeDir("HOME");a("#btnReloadDirTree").blur();a.isFunction(b)&&setTimeout(b,1E3);a.zoomBatch.dirLoaderEnd();a.zoomBatch.dirLoaderOverlayEnd()}})};a.zoomBatch.batchFilterNeedCache=function(b,c){a.zoomBatch.dirLoaderStart();a.zoomBatch.dirLoaderOverlayStart();a.ajax({url:a.zoomBatch.batch.selfFile+"?reloadDirTree=1&filterNeedCache="+
b,timeout:36E4,cache:!1,dataType:"script",success:function(b){a.zoomBatch.changeDir("HOME");a("#btnReloadDirTree, #buttonFilterNeedCache").blur();a.isFunction(c)&&setTimeout(c,1E3);console.log(a.zoomBatch.reloadDirTreeReturn);a.zoomBatch.dirLoaderEnd();a.zoomBatch.dirLoaderOverlayEnd()}})};a.zoomBatch.dirLoaderOverlayStart=function(){a("<div />").addClass("zFsOResOverlay").css({position:"fixed",width:"100%",height:"100%",zIndex:999,opacity:0,top:0,left:0}).on("click",function(a){a.stopPropagation();
a.preventDefault();return!1}).appendTo("body").fadeTo(200,.5)};a.zoomBatch.dirLoaderOverlayEnd=function(){a("body>.zFsOResOverlay").stop(!0,!1).fadeOut(200,function(){a(this).remove()})};a.zoomBatch.dirLoaderStart=function(){a("#dirLoader").css("visibility","visible").addClass("dirLoaderSpin").stop(!0,!1).fadeTo("fast",1)};a.zoomBatch.dirLoaderEnd=function(){a("#dirLoader").stop(!0,!1).fadeTo("fast",0,function(){a(this).removeClass("dirLoaderSpin")})};a.zoomBatch.changeDir=function(b,c){a.zoomBatch.dirLoaderStart();
a.ajax({url:a.zoomBatch.batch.selfFile+"?dirReplace=1&dir="+b,timeout:36E4,cache:!1,dataType:"script",success:function(d){a("#batchSelect").val(b);a.zoomBatch.bc(b);a.zoomBatch.currentDir=b;a.isFunction(c)&&setTimeout(c,100);a.zoomBatch.dirLoaderEnd()}})};a.zoomBatch.deleteZoom=function(b){var c=function(b){a.ajax({url:a.zoomBatch.batch.selfFile+"?delPic="+b,timeout:36E4,cache:!1,dataType:"script",success:function(a){}})};a.zoomBatch.batch.confirmDelete?confirm("Do you really want to delete all \najax-zoom created files for this image?\n\nThe image itself will not be deleted!")&&
c(b):c(b)};a.zoomBatch.checkSelected=function(b){var c=a("#passFiles input[type=checkbox]:checked").length;return b||0!=c?!0:(alert("No images or folders selected!"),!1)};a.zoomBatch.checkFolderSelected=function(){return a(".checkBoxFolder:checked").length};a.zoomBatch.batchDelete=function(){var b=function(){a.zoomBatch.ajaxSubmitCustom("#passFiles","?submitDelete=1");a("#passFiles input").attr({disabled:!0});a("#leftFrameFoot input").attr({disabled:!0});var b='<div class="processMsg alert alert-info clearfix" id="processMsgNotice">'+
(a.zoomBatch.batch.iconInfo+"Delete process started, please wait!");b+="</div>";a("#batchProcess").append(b)};if(!a.zoomBatch.checkSelected())return!1;a.zoomBatch.batch.confirmDelete?confirm("Do you really want to delete all \najax-zoom created files for the selected images?\n\nThe source images will not be deleted!")&&b():b()};a.zoomBatch.clearBatchResults=function(b){a(".processMsg").remove();a("table.batchProcessTable tbody tr").remove();a("table.batchProcessTable").css("display","none");b||a("#batchAbout").slideDown(200)};
a.zoomBatch.ajaxSubmitCustom=function(b,c){a.ajax({type:"POST",url:a.zoomBatch.batch.selfFile+c,data:a(b).serialize(),timeout:36E4,cache:!1,dataType:"script",success:function(a){}});return!1};a.zoomBatch.batchStop=function(){a.zoomBatch.dirLoaderStart();a("#buttonBatchStop").addClass("disabled").attr({disabled:!0});a.ajax({url:a.zoomBatch.batch.selfFile+"?batchStop=1",timeout:36E4,cache:!1,success:function(b){a.zoomBatch.shortMsg("Batch process has been aborted. Please wait!");a("#buttonBatchStop").fadeOut(200)}})};
a.zoomBatch.stopBatchAfter=function(){a("#batchCounterDiv").empty();a("#batchProgressBar").stop(!0,!1).css("width",0);a.zoomBatch.clearBatchResults();a.zoomBatch.dirLoaderEnd();a.zoomBatch.reload();a("#leftFrameFoot input, #leftFrameFoot button").attr({disabled:!1});a("#buttonBatchStop").fadeOut(200);a.zoomBatch.isRunning=!1;if(navigator.wakeLock)try{navigator.wakeLock.release("display"),navigator.wakeLock.release("system")}catch(b){}};a.zoomBatch.batchSubmit=function(b){if(!b&&!a.zoomBatch.checkSelected()||
!b&&a.zoomBatch.batch.confirmBatch&&(b=a(".checkBoxFolder:checked").length,0<b&&!confirm("Do you want to start batch process in "+b+" folders and all the subfolders? This confirmation does not appear,\nif you select single images")))return!1;a("#buttonBatchStop").removeClass("disabled").fadeIn(200);a.zoomBatch.ajaxSubmitCustom("#passFiles","?submitList=1");a("#passFiles input").attr({disabled:!0});a('#leftFrameFoot input, #leftFrameFoot button:not("#buttonBatchStop")').attr({disabled:!0});a.zoomBatch.clearBatchResults(!0);
a(".batchInfo, .batchSettings").css("display","none");a("table.batchProcessTable").css("display","table");b=a.zoomBatch.batch.iconInfo+" Batch process started, please wait!";a("#batchProcess").append('<div class="processMsg alert alert-info clearfix" id="processMsgNotice">'+b+"</div>");a.zoomBatch.isRunning=!0;if(navigator.wakeLock)try{navigator.wakeLock.request("display"),navigator.wakeLock.request("system")}catch(c){}};a.zoomBatch.getNumberImages=function(b,c){if(!a.zoomBatch.isRunning)if(b){a("#batchFilesInfoResults").empty().html("Loading, please wait...");
a("#batchFilesInfoTableResults").empty();var d=a("#getNumberImagesWithPath").is(":checked")?1:0,e=a("#getNumberImagesToProcess").is(":checked")?1:0;a.zoomBatch.dirLoaderOverlayStart();a.ajax({type:"POST",url:a.zoomBatch.batch.selfFile+"?getNumberImages=1&depth="+b+"&withPaths="+d+"&needToProcess="+e,data:a("#passFiles").serialize(),timeout:36E4,cache:!1,success:function(d){c&&a(c).blur();var e=JSON.parse(d);d="";d="The number of images in selected folders is: <strong>"+e.numImages+"</strong>";d+=
"<br><small>request time: "+e.time+" seconds</small>";a("#batchFilesInfoResults").empty().html(d);if(1!=b&&0<parseInt(e.numImages)){if(2==b)var f='<table class="table table-striped"><thead><th>Filename</th></thead><tbody></tbody></table>';else 3==b&&(f='<table class="table table-striped"><thead><th>Filename</th><th style="width: 80px">Image size</th><th style="width: 55px">Filesize</th></thead><tbody></tbody></table>');d=a(f);var h="",l=d.find("tbody");a.each(e.imgNames,function(c,d){h="<tr>";h+=
"<td>"+d+"</td>";3==b&&(h+="<td>"+e.imgInfo[c][0]+"</td>",h+="<td>"+e.imgInfo[c][1]+"</td>");h+="</tr>";a(h).appendTo(l)});d.appendTo("#batchFilesInfoTableResults")}a("#batchFilesInfo").is(":visible")||a.zoomBatch.toggleSettingTab("batchFilesInfo");a.zoomBatch.dirLoaderOverlayEnd()}})}else a("#batchFilesInfoResults").empty(),a("#batchFilesInfoTableResults").empty(),a("#batchFilesInfo").is(":visible")||a.zoomBatch.toggleSettingTab("batchFilesInfo")};a.zoomBatch.switchBatch=function(b){if(a.zoomBatch.isRunning)a.zoomBatch.isRunningMsg();
else{var c=a("#batchSwitch"+b).is(":checked")?"on":"off";a.zoomBatch.dirLoaderStart();a("#leftFrameFoot input").attr({disabled:!0});a.ajax({url:a.zoomBatch.batch.selfFile+"?switchBatch="+b+"_"+c,timeout:1E4,cache:!1,dataType:"script",success:function(b){a.zoomBatch.dirLoaderEnd();a("#leftFrameFoot input").attr({disabled:!1})}})}};a.zoomBatch.adjHeights=function(b){if(!a.zoomBatch.adjHeightsTime)a.zoomBatch.adjHeightsTime=(new Date).getTime();else if(100>(new Date).getTime()-a.zoomBatch.adjHeightsTime)return;
var c=parseInt(a(window).height()),d=parseInt(a("#batchProcessHead").outerHeight()),e=parseInt(a("#leftFrameFoot").outerHeight()),f=0;a("#rightFrameFoot").length&&a("#rightFrameFoot").is(":visible")&&(f=parseInt(a("#rightFrameFoot").outerHeight()));var g=parseInt(a("#bci").outerHeight())+1,k=0,h=0;a("#batchNavbar").is(":visible")&&(k=parseInt(a("#batchNavbar").outerHeight()));a("#filesNavbar").is(":visible")&&(h=parseInt(a("#filesNavbar").outerHeight()));a("#batchList").animate({height:c-d-2*g-e-
2-h},{queue:!1,duration:b,easing:"swing"});a("#batchProcess").animate({height:c-d-2*g-f-2-k},{queue:!1,duration:b,easing:"swing"})};a.zoomBatch.trOver=function(){a("td:eq(1)",a("#leftFrameFolder tr")).each(function(){var b=a(this),c=b.attr("data-folder");c&&(b.prev().find("i").bind("click",function(){b.trigger("dblclick")}).bind("mouseenter",function(){a(this).addClass("fa-folder-open")}).bind("mouseleave",function(){a(this).removeClass("fa-folder-open")}),b.bind("dblclick",function(d){a.zoomBatch.changeDir(c);
b.parent().removeClass("oneClick");d.preventDefault()}).bind("click",function(){b.parent().addClass("oneClick");setTimeout(function(){if(b.length){b.parent().removeClass("oneClick");var a=b.next().find("input[type=checkbox]");a.prop("checked")||a.attr("checked")?a.prop("checked",!1).attr("checked",!1):a.prop("checked",!0).attr("checked",!0)}},500)}))});a("#passFiles input[type=checkbox]").each(function(){var b=a(this).attr("name").split("f").join("");b&&-1==b.indexOf("[")&&(a("#fname"+b).bind("click",
function(){a.zoomBatch.toggleCheckBox("f"+b)}),a("#fname"+b).bind("mouseover",function(){a("#d"+b).addClass("fileHover");a("#d"+b+" td").addClass("fileHover")}),a("#fname"+b).bind("mouseout",function(){a("#d"+b).removeClass("fileHover");a("#d"+b+" td").removeClass("fileHover")}))})};a.zoomBatch.previewPic=function(b,c,d,e){var f=a("#prev"+b).offset();c||(c=a("#prev"+b).attr("data-img"));if(c){a(".imgPrevDiv").remove();var g=parseInt(a(window).height()),k=a.zoomBatch.batch.previewWidth/2,h=a.zoomBatch.batch.previewHeight/
2,l=k/d>h/e?h/e:k/d;k=Math.round(d*l);h=Math.round(e*l);f.top=f.top+h>g-40?g-40-h:f.top;d='<div class="imgPrevDiv" style="width: '+(k+22)+"px; height: "+(h+22)+"px; left: "+(f.left+46)+"px; top: "+f.top+'px;" id="prv'+b+'">';d=d+('<div class="imgPrevDiv1 imgPrevDiv_loading" style="width: '+(k+22)+"px; height: "+(h+22)+'px;">')+('<img src="'+a.zoomBatch.batch.config.icon+'empty.gif" id="prvImg'+b+'">');d+="</div></div>";var m=(new Date).getTime(),n=function(){a.zoomBatch.previewPicUnload=setTimeout(function(){a("#prv"+
b).fadeOut(200,function(){a("#prv"+b).remove()})},500)};a("<img>").axZmLoad(function(){var d=(new Date).getTime()-m;a("#prvImg"+b).attr("src","?previewPic="+c+"&rand="+m).css({width:k,height:h});a("#prvImg"+b).parent().append('<span class="imgPrevDiv2">Loading time: '+d+" ms</span>");a("#prvImg"+b).parent().removeClass("imgPrevDiv_loading")}).attr("src","?previewPic="+c+"&rand="+m);a("body").append(d);a("#prvImg"+b).mouseenter(function(){a(this).unbind("mouseenter");clearTimeout(a.zoomBatch.previewPicUnload)}).mouseleave(function(){a(this).unbind("mouseleave");
n()});a("#prev"+b).mouseleave(function(){a(this).unbind("mouseleave");n()})}};a.zoomBatch.toggleSettingTab=function(b,c,d){a.fn.axZm.removeAZ();d&&a(d).blur();a.zoomBatch.isRunning?a.zoomBatch.isRunningMsg():!a("#"+b).is(":visible")&&b&&(a.zoomBatch.clearBatchResults(),a(".batchSettings, .batchInfo").hide(),a("#"+b).slideDown(200,c))};a.zoomBatch.updateProgressBar=function(b,c){var d=parseInt(a("#batchProcessHead").outerWidth());d=Math.floor(b/c*d);a("#batchProgressBar").animate({width:d},{duration:Math.min(a.zoomBatch.batch.pause,
200),easing:"linear"})};a.zoomBatch.setOtherSettings=function(){var b={};a("input, select",a("#batchSettingOther")).each(function(){var c=a(this);"checkbox"==this.type?b[this.name]=c.is(":checked")?!0:!1:(c=c.val(),parseInt(c)==c&&(c=parseInt(c)),b[this.name]=c);a.zoomBatch.batch[this.name]=b[this.name]});a.ajax({type:"POST",url:a.zoomBatch.batch.selfFile+"?setOtherSettings=1",data:b,cache:!1,success:function(c){b.enableBatchThumbs?a("#processTable th:eq(0)").css("display","table-cell"):a("#processTable th:eq(0)").css("display",
"none");a.zoomBatch.shortMsg("Settings have been submitted.")}})};a.zoomBatch.submitDynImagesValues=function(){var b={},c=0;a("#batchDynImgForm .row.form").each(function(){var d=a(this),e=a('input[name="batchDynImgWidth"]',d).val(),f=a('input[name="batchDynImgHeight"]',d).val(),g=a('input[name="batchDynImgQual"]',d).val();d=a('select[name="batchDynImgThumbMode"]',d).val();e&&f&&g&&(c++,100<g&&(g=100),b[c]={width:e,height:f,qual:g,thumbMode:d})});a.ajax({type:"POST",url:a.zoomBatch.batch.selfFile+
"?setDynImageSizes=1",data:{dynImageSizes:b},cache:!1,success:function(c){a.zoomBatch.batch.dynImageSizes=b;a.zoomBatch.dynImageSizesSet();a.zoomBatch.reload();a.zoomBatch.shortMsg("Setting has been submitted.")}})};a.zoomBatch.dynImageSizesSet=function(b){a("#batchDynImgForm").empty();b||Object.keys(a.zoomBatch.batch.dynImageSizes).length?a.each(b||a.zoomBatch.batch.dynImageSizes,function(b,d){a.zoomBatch.dynImageSizesAppend(d)}):a.zoomBatch.dynImageSizesAppend()};a.zoomBatch.dynImageSizesAppend=
function(b,c){b=b||{};var d=a("#batchDynImgTemplate").clone().css("display","").removeAttr("id"),e=a("#batchDynImgForm");a('input[name="batchDynImgWidth"]',d).val(b.width||"");a('input[name="batchDynImgHeight"]',d).val(b.height||"");a('input[name="batchDynImgQual"]',d).val(b.qual||"");a('select[name="batchDynImgThumbMode"]',d).val(b.thumbMode||"false");a("button",d).bind("click",function(){a(this).closest(".row.form").remove()});d.appendTo(e);c&&a(c).blur()};a.zoomBatch.submitFilters=function(){var b=
{filterFiles:[],filterFolders:[]};a("#batchFilterFormFiles .row.form").each(function(){var c=a(this);(c=a('input[name="batchFilterString"]',c).val())&&b.filterFiles.push(c)});a("#batchFilterFormFolders .row.form").each(function(){var c=a(this);(c=a('input[name="batchFilterString"]',c).val())&&b.filterFolders.push(c)});b.filterResolution=a('input[name="batchFilterResolution"]').val();a.ajax({type:"POST",url:a.zoomBatch.batch.selfFile+"?setFilters=1",data:b,cache:!1,success:function(c){a.zoomBatch.batch.resolutionFilter=
b.filterResolution;a.zoomBatch.setFilterLines(b.filterFiles,b.filterFolders);JSON.stringify(a.zoomBatch.batch.foldersFilter)!=JSON.stringify(b.filterFolders)?a.zoomBatch.reloadDirTree():a.zoomBatch.reload();a.zoomBatch.batch.foldersFilter=b.filterFolders;a.zoomBatch.batch.filesFilter=b.filterFiles;a.zoomBatch.shortMsg("Settings have been submitted.")}})};a.zoomBatch.setFilterLines=function(b,c){a("#batchFilterFormFiles").empty();a("#batchFilterFormFolders").empty();b&&b.length||a.zoomBatch.batch.filesFilter&&
Object.keys(a.zoomBatch.batch.filesFilter).length?a.each(b||a.zoomBatch.batch.filesFilter,function(b,c){a.zoomBatch.appendFilterLine("Files",c)}):a.zoomBatch.appendFilterLine("Files");c&&c.length||a.zoomBatch.batch.foldersFilter&&Object.keys(a.zoomBatch.batch.foldersFilter).length?a.each(c||a.zoomBatch.batch.foldersFilter,function(b,c){a.zoomBatch.appendFilterLine("Folders",c)}):a.zoomBatch.appendFilterLine("Folders");a('input[name="batchFilterResolution"]').val(a.zoomBatch.batch.resolutionFilter)};
a.zoomBatch.appendFilterLine=function(b,c,d){var e=a("#batchFilterTemplate").clone().css("display","").removeAttr("id");b=a("#batchFilterForm"+b);a('input[name="batchFilterString"]',e).val(c||"");a("button",e).bind("click",function(){a(this).closest(".row.form").remove()});e.appendTo(b);d&&a(d).blur()};a.zoomBatch.setCellIcon=function(b,c){var d=a(b);d.attr("class")!=a.zoomBatch.batch.iconNames.Nn&&d.attr("class",c)};a.zoomBatch.setCellIconDone=function(b,c){var d=b.replace("Mk","");a(d).attr("class")==
a.zoomBatch.batch.iconNames.Nn?a(b+" i").attr("class",a.zoomBatch.batch.iconNames.Nn):a(b+" i").attr("class",c)};a.zoomBatch.saveBatchSettings=function(){location.href=a.zoomBatch.batch.selfFile+"?saveBatchSettings=1"};a.zoomBatch.loadBatchSettings=function(b,c){if(window.File&&window.FileReader&&window.FileList&&window.Blob){var d=b.target.files;if(d[0])if("application/json"!=d[0].type)alert("Not a JSON file.");else{d=d[0];var e=new FileReader;e.onload=function(b){try{var c=JSON.parse(e.result)}catch(k){alert("The file is not valid JSON file");
return}a.isPlainObject(c)?a.ajax({type:"POST",url:a.zoomBatch.batch.selfFile+"?loadBatchSettings=1",data:{loadBtchSettings:c},cache:!1,success:function(b){a.each(c,function(b,c){void 0!=a.zoomBatch[b]&&(a.zoomBatch[b]=c);void 0!=a.zoomBatch.batch[b]&&(a.zoomBatch.batch[b]=c)});a.zoomBatch.reloadDirTree();a.zoomBatch.dynImageSizesSet();a.zoomBatch.setFilterLines();a.zoomBatch.shortMsg("Your settings are loaded.")}}):a.zoomBatch.shortMsg("Your settings are not loaded.")};e.readAsText(d)}}else alert('You browser does not support "File APIs"')};
a.zoomBatch.loadPreset=function(b){(b=a.zoomBatch.batch.presets[b])&&b.startPic&&(console.log(b.startPic),a.zoomBatch.submitStartPicBatch(b.startPic))};a.zoomBatch.showInPlayer=function(b,c){a("#batchViewInPlayer").is(":visible")||a.zoomBatch.toggleSettingTab("batchViewInPlayer");c&&a(c).blur();a.fn.axZm.removeAZ();a("#batchViewPlayer").empty().append('<div class="batchViewPlayerIdle"></div>');a("#batchViewPlayer360Options").css("display","none");a("#batchViewPlayerOptions").css("display","none");
if(b){if("gallery"==b){var d=a("#leftFrameTable input:checked");if(!d.length&&1===a("#leftFrameFolder input:checked").length){var e=a("#leftFrameFolder input:checked").val();if(!a.zoomBatch.dirTreeArray[e+"_1"]){var f=a.zoomBatch.dirTreeArray[e];var g="zoomDir="+f.DIR_PATH}}if(!g&&(d.length||(d=a("#leftFrameTable input")),d.length)){var k=[];f=a.zoomBatch.dirTreeArray[a.zoomBatch.currentDir];a.each(d,function(){var b=parseInt(a(this).attr("id").replace("f",""));b=f.DIR_PATH+"/"+a.zoomBatch.pic_list_array[b];
b=b.replace("//","/");k.push(b)});g="zoomData="+k.join("|")}if(!g){a.zoomBatch.shortMsg("Error selecting content to laod.");return}}else if("360"==b)if(1<a("#leftFrameFolder input:checked").length)a.zoomBatch.shortMsg("Please selct only one folder for a single row 360 spin view.");else if(1===a("#leftFrameFolder input:checked").length)e=a("#leftFrameFolder input:checked").val(),a.zoomBatch.dirTreeArray[e+"_1"]?a.zoomBatch.shortMsg("There are subfolders under the selected folder. Cannot load 360 view."):
(f=a.zoomBatch.dirTreeArray[e],g="3dDir="+f.DIR_PATH);else if(a.zoomBatch.pic_list_array[1]&&!a("#leftFrameFolder input").length)f=a.zoomBatch.dirTreeArray[a.zoomBatch.currentDir],g="3dDir="+f.DIR_PATH;else{a.zoomBatch.shortMsg("Error, no images in this folder or there are subfolders in this folder.");return}else"3d"==b&&(1==a("#leftFrameFolder input:checked").length?(e=a("#leftFrameFolder input:checked").val(),a.zoomBatch.dirTreeArray[e+"_1"]&&a.zoomBatch.dirTreeArray[e+"_2"]?(f=a.zoomBatch.dirTreeArray[e],
g="3dDir="+f.DIR_PATH):a.zoomBatch.shortMsg("There are no subfolders in the selected folder.")):a("#leftFrameFolder input:checked").length==a("#leftFrameFolder input").length&&1<a("#leftFrameFolder input:checked").length?(f=a.zoomBatch.dirTreeArray[a.zoomBatch.currentDir],g="3dDir="+f.DIR_PATH):1<a("#leftFrameFolder input:checked").length?a.zoomBatch.shortMsg("If you select a folder, please select only one folder, which contains more than one subfolder."):1==a("#leftFrameFolder input").length?(e=
a("#leftFrameFolder input").val(),a.zoomBatch.dirTreeArray[e+"_1"]&&a.zoomBatch.dirTreeArray[e+"_2"]?(f=a.zoomBatch.dirTreeArray[e],g="3dDir="+f.DIR_PATH):a.zoomBatch.shortMsg("There are no subfolders in this directory or there is only one subfolder.")):1<a("#leftFrameFolder input").length?(f=a.zoomBatch.dirTreeArray[a.zoomBatch.currentDir],g="3dDir="+f.DIR_PATH):a.zoomBatch.shortMsg("Error, nothing to load for 3D."));g&&(d="example="+a.zoomBatch.batch.exampleValue,jQuery.fn.axZm.openResponsive("",
d+("&"+g),{onSpinPreloadEnd:function(b){b&&!1===b.g&&a.zoomBatch.reload();a("#batchViewPlayer360Options").css("display","block")},onLoad:function(){"gallery"==b&&(a.zoomBatch.reload(),a.axZm.zoomGA[2]&&a("#batchViewPlayerOptions").css("display","block"))},onImageChangeEnd:function(){"gallery"==b&&a.zoomBatch.reload()}},"batchViewPlayer",!1,!0,!1))}};a.zoomBatch.spinReverseToggle=function(b){b&&a(b).blur();a.axZm&&(a.axZm.spinReverse=a.axZm.spinReverse?!1:!0)};a.zoomBatch.spinReverseZToggle=function(b){b&&
a(b).blur();a.axZm&&(a.axZm.spinReverseZ=a.axZm.spinReverseZ?!1:!0)};a(window).load(function(){window.chrome&&window.chrome.webstore&&a("#batchList, #batchProcess").addClass("batchScrollbar");a("#buttonSelectAll").click(function(){a.zoomBatch.selectAllCheckbox("passFiles");a(this).blur()});a("#buttonSelectAllFolders").click(function(){a.zoomBatch.selectAllCheckboxFolders("passFiles");a(this).blur()});a("#buttonSelectAllImages").click(function(){a.zoomBatch.selectAllCheckboxImages("passFiles");a(this).blur()});
a("body").on("click","#buttonSelectAllImagesClone",function(){a.zoomBatch.selectAllCheckboxImages("passFiles");a(this).blur()});a("body").on("click","#buttonSelectAllFoldersClone",function(){a.zoomBatch.selectAllCheckboxFolders("passFiles");a(this).blur()});a("body").on("click","#buttonChangeHomeDir",function(){a.zoomBatch.toggleSettingTab("batchSettingStartPic",null,this)});a("#buttonBatchStop").click(function(){a.zoomBatch.batchStop();a(this).blur()});a("#buttonBatch").click(function(){a.zoomBatch.batchSubmit();
a(this).blur()});a.zoomBatch.batch.allowBatchDelete&&a("#buttonDelete").click(function(){a.zoomBatch.batchDelete();a(this).blur()});a("#buttonSmartSelect").click(function(){a.zoomBatch.smartSelect();a(this).blur()});setTimeout(function(){a.zoomBatch.adjHeights(0)},250);a.zoomBatch.trOver();a.zoomBatch.bc("HOME");a.zoomBatch.dynImageSizesSet();a.zoomBatch.setFilterLines();setInterval(function(){a.zoomBatch.isRunning||a.ajax({type:"GET",url:a.zoomBatch.batch.selfFile+"?keepLogin=1",cache:!1})},12E4)}).bind("resize",
function(){a.zoomBatch.adjHeights(0)})})(jQuery);